language: node_js
node_js:
  - "7"

install:
  - npm install

script:
  - npm run eslint src/
  - npm test
  - npm run webpack

sudo: required

services:
  - docker

after_success:
  - npm run provision
