env:
  global:
  - secure: MTFZTANzQNeMV7LtAxi1JDncc4uACZxi1As/2wzZ6RO71KxP6xe76iMNZtFELcyqrNZ99mBD6ohcxWXCyui3MFGvH6FF0JKJwzPB+FFAVZsI596KnDxewz4XZKAWAmGi2jhQpXw3sSDcNFo2t0sjFsbICrVr9fbIPmKMzCoFGx+7bzP7cWa3tJLocFz5QEeH5jIx0mqo2HM6DR/1yKiscuc2k+I11POsLrk2Kpax0qcWnN2xQePoihMjhNVIemu8JBGHStYdEFDhxVR6Z2Mw4WwTCKYVp0+E5YocUKZHo/zVHRnbEUBlCGJG4Hz2Ls7j++SNVwGHpVj3EupqxMESx2C8yv8cXJDeyrEbaMzdNwbYcqmoOBmXoLv8Ved9eXujgZ6lI+ohcMoVpnRzs5HWvXELoWMQCVSJPnkrlAhZJ3Zr6ibRH1ftRyn8/lcgIuQdzV3VV1d5zzahEgR/X8TTYFltj577sZt/lh4P+Do346GPI+5KuQTeaB8qifHwxfO+P6YTBdWiK4cGqkVyjBCKqDVdccbTHIjftFrlWBh+wQmhTEqhZ5rKLIN2V3a6V6J6ZIdt5fLTP2vlwK26GDDVFSTIEdBlpdWG68qIdjJwH5nGaLm/bABE1CQ1NL5RpAKEASvq0R9Mglvpj+DYTHGtBuWaS4Vkqin5Wvyfd7tpjPg=
  - secure: flp6c2V3cR68B7n/Rk3KxCwHJy3gjQ0bgr5uuTQB+X+TnQZc3DWM1dJ3AThHzP3muG4MlUHhyQbgSbNCV2o6v4Qt2PsnOyvWmr6uaEdpE9eHiXhtKNIvakKAP0OEOl9eAjumXI1tX67hOFkeo9KNgtWRaNlq9tgbArdttr4G4nnLJJ7YWKUila+XSfq9Ajuynd35/sRDByfx5WCubHDJybKZzTBW7hGLCu9uws06+2R2BfjjtK4hA4B3BbmzKw8hNrRCDxUVI1Ob2CJeIS/kjzYasKIaqcvtwHSaWqygN76xMBZXZffTJDdhxALH8WKO46u/d3uDucJzUiJ4vU9saKn8U7rBGWVUOSI9PFa2/qDd49V1biAvm68+Fs65taqL17fKGHwIL0jvzDcmGbyh9EpB4bhviyL5yVHWdWuk3vJBYxKCZ7/BDtFVs1Qm0p/iT/mQ/c6v6ZZUYrc/pbp/ehMLVVSLD/jRBCko6m5XL7KQgRQZK9OFR8MVk9cUtaaTt+NyOEBxslYJywSGLoWCw7VQVKx/TTMjBiNOFOyfDrhGwXorMdJHIQMUnVxroVSeDYJOPmoLhGFnB8z29GVNVn7bKXv9SKaBw3MHwNZbUIKy62JhYHfjVtvq7RiPNFviGwXm9F/iEUahupdH/c4C9tZA6UAqUaTtFPEHjzPnjLI=
  - secure: b8KE6DtOSv2yLKoSjEXE8K+KOYRQFl+ij27CcMkItTv7SSoLGhyohnuLHJLz3uBCMM396VnR+8GiWqmmnDy1kK1tS4dGR0lnvA6JoNbjaMBU6HEesOITqg+xNIwOtxp4hD5xY7CN25SNBc9Dy8CdsjcwO+TfN1IK6MF1J71CfWpOPUJSDl0pGyS/H4p9IoGeBDFgc5WpVxhH2yzWHNw/jYeUCOZXmv2pzaBYNN2jUBtHjgaeAcKPQfS9rLZN9OrQlAAZZQQX6KxYv/ITubxBRO9glp94A0lZVQ9t7t+vAyJnZFhQReAfLjZz/63BicnjzC2LrA8NwweEJ3kSqiRu8zeQbUnwLA0+/h8vBDxtr7lmKUdB7NID57lAWULHvvdaf1MhVoGqjPkjAb2zubD5i8WmgU4JDnKWwGIxSd95fVR6NvmlL2XL7453u8PV/j9e5cqYnzr68DwizY46paVW0SuDesvc7804bsinpfg21MxjHSw8fsS0W1ULLgZfD8ZRht0eO8ScHuefnvJwu93ccqZywBkBE8Y9wT4CDSm887BPUu8c7IhJeR9yudFU9zqnma471yIQvncDnSx0C3GIGqdq7WhjokUMb28tUhhLvtyfdCm5jD/KmxbXanIZgaCDQphwJbV6O2tuo4eUTqx2MbnqV1Vo0k31/RyVP4KQ0UQ=
language: node_js
node_js:
- '7'
install:
- npm install
script:
- npm run eslint src/
- npm test
- npm run webpack
sudo: required
services:
- docker
after_success:
- npm run provision
- curl --ftp-create-dirs -T /demo -u $FTP_USER:$FTP_PASSWORD $FTP_URL
