export default (text) => {
    const books = [
        ['Gen','1. Mo','1 Mo'],
        ['Ex'],
        ['Lev'],
        ['Num'],
        ['Dtn'],
        ['Jos'],
        ['Ri'],
        ['Rut'],
        ['1 Sam'],
        ['2 Sam'],
        ['1 Kön'],
        ['2 Kön'],
        ['1 Chr'],
        ['2 Chr'],
        ['Esra'],
        ['Neh'],['Tob'],['Jdt'],
        ['Est'],['1 Makk'], ['2 Makk'],
        ['Ijob'],
        ['Ps'],
        ['Spr'],
        ['Koh'],
        ['Hld'],['Weish'],['Sir'],
        ['Jes'],
        ['Jer'],
        ['Klgl'],['Bar'],
        ['Ez'],
        ['Dan'],
        ['Hos'],
        ['Joel'],
        ['Am'],
        ['Obd'],
        ['Jona'],
        ['Mi'],
        ['Nah'],
        ['Hab'],
        ['Zef'],
        ['Hag'],
        ['Sach'],
        ['Mal'],
        ['Mt'],
        ['Mk'],
        ['Lk'],
        ['Joh'],
        ['Apg'],
        ['Röm'],
        ['1 Kor'],
        ['2 Kor'],
        ['Gal'],
        ['Eph'],
        ['Phil'],
        ['Kol'],
        ['1 Thess'],
        ['2 Thess'],
        ['1 Tim'],
        ['2 Tim'],
        ['Tit'],
        ['Phlm'],
        ['Hebr'],
        ['Jak'],
        ['1 Petr'],
        ['2 Petr'],
        ['1 Joh'],
        ['2 Joh'],
        ['3 Joh'],
        ['Jud'],
        ['Offb'],
    ];

    const flatten = (arrays) => [].concat.apply([], arrays);
    const escapeRegExp = (str) => str.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g, "\\$&");

    const bookRegExpString = `(${flatten(books).map(escapeRegExp).join('|')})`;
    const re = new RegExp(`${bookRegExpString}\.? [0-9]{1,3},[0-9]{1,3}`, 'g');
    return text.match(re) || [];
}